### ISSUE TITLE
No instructions on how to create secret `chiakey` in README.md

### ISSUE THREAD

**Issue by skandragon** [Chia-Network/chia-operator#112]
Should go over how to generate your key, what the secret looks like, etc.

**Comment by Starttoaster** [comment]
Thanks for the suggestion! I'm working on a PR that refines the documentation a bit, I'll add this suggestion to the docs there! Until then, this is what a basic Secret yaml looks like:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: chiakey
stringData:
  key.txt: <your mnemonic>
type: Opaque
```

The important details to remember are the Secret's name, and the key in the Secret you used, which in this case would be `key.txt`. You'd reference both of those in your ChiaWallet or ChiaFarmer yaml.
